Update cp scripts

diff --git a/bin/cpInit b/bin/cpInit
--- a/bin/cpInit
+++ b/bin/cpInit
@@ -1,8 +1,144 @@
 #!/bin/bash
 
-TEMPLATE_PATH=/home/edvin/Programming/codeforces/template.cpp
+# Functions
+function print_help {
+	SCRIPT_NAME=$(basename $BASH_SOURCE)
+	echo -e "USAGE"
+	echo -e "\t$SCRIPT_NAME [OPTION]... <file[.cpp]>"
+	echo -e "\t\tInitialize a new c++ file from a template\n"
+	echo -e "\t$SCRIPT_NAME [-h]\n\t\tDisplay this text\n"
+
+	echo -e "ARGUMENTS"
+	echo -e "\tfile"
+	echo -e "\t\tThe file to create, this script does nothing if the file already exist\n"
+
+	echo -e "OPTIONS"
+	echo -e "\t-h\n\t\tDisplay this text\n"
+	echo -e "\t-s\n\t\tThere should only be one single testcase\n"
+	echo -e "\t-t={s|solution|v|validator|g|generator}\n\t\tThe type of template to generate. Default is 'solution'.\n"
+
+	exit 1
+
+}
+
+# Template strings
+SOLVE_FN_NAME="solveTestcase"
+GEN_FN_NAME="genTestcase"
+
+TEMPLATE_HEADER=$(cat <<-END
+#include <bits/stdc++.h>
+using namespace std;
+
+using ull = unsigned long long;
+using ll = long long;
+using llp = pair<ll,ll>;
+using ullp = pair<ull,ull>;
+
+END
+)
+
+TEMPLATE_SOLVE_FN=$(cat <<-END
+void $SOLVE_FN_NAME() {
+}
+
+END
+)
+
+TEMPLATE_GEN_FN=$(cat <<-END
+void $GEN_FN_NAME(mt19937& rng) {
+    uniform_int_distribution<ll> distr(0, 10);
+}
+
+END
+)
+
+TEMPLATE_MAIN_HEADER=$(cat <<-END
+int main(int argc, char* argv[]) {
+    ios_base::sync_with_stdio(false);
+    cin.tie(NULL);
+
+END
+)
+
+TEMPLATE_TESTCASES=$(cat <<-END
+    int t;
+    cin >> t;
+
+    for(int tc = 0; tc < t; ++tc) {
+        $SOLVE_FN_NAME();
+    }
+
+END
+)
+
+TEMPLATE_TESTCASE=$(cat <<-END
+    $SOLVE_FN_NAME();
+END
+)
+
+TEMPLATE_RNG=$(cat <<-END
+    ll seed = atoi(argv[1]);
+    mt19937 rng(seed);
+
+
+END
+)
+
+TEMPLATE_CALL_GEN=$(cat <<-END
+    $GEN_FN_NAME(rng);
+
+END
+)
+
+# Variables
+TYPE="solution"
+SINGLE_TESTCASE_FLAG=false
+
+# Parse arguments
+while getopts hst: opt
+do
+	case "${opt}" in
+		h) print_help;;
+		s) SINGLE_TESTCASE_FLAG=true;;
+		t) TYPE=${OPTARG};;
+		*) print_help;;
+	esac
+done
+shift $((OPTIND - 1))
+
+
 FILE="${1%.*}.cpp"
 
-if  [[ ! -f "$FILE" ]]; then
-    cp "$TEMPLATE_PATH" $FILE && nvim $FILE
+# Validate arguments
+if [[ $# != 1 ]]; then
+	echo -e "ERROR: No file specified\n"
+	print_help
+fi
+
+
+# Create file from template
+TEMPLATE=""
+TEMPLATE_CALL_TESTCASE="$TEMPLATE_TESTCASES"
+if [[ $SINGLE_TESTCASE_FLAG == true ]]; then
+	TEMPLATE_CALL_TESTCASE="$TEMPLATE_TESTCASE"
+fi
+
+if [[ $TYPE == "solution" || $TYPE == "s" ]]; then
+	TEMPLATE=$(echo -e "$TEMPLATE_HEADER\n\n$TEMPLATE_SOLVE_FN\n\n$TEMPLATE_MAIN_HEADER\n\n$TEMPLATE_CALL_TESTCASE\n}" )
+elif [[ $TYPE == "validator" || $TYPE == "v" ]]; then
+	TEMPLATE=$(echo -e "$TEMPLATE_HEADER\n\n$TEMPLATE_SOLVE_FN\n\n$TEMPLATE_MAIN_HEADER\n\n$TEMPLATE_CALL_TESTCASE\n}" )
+elif [[ $TYPE == "generator" || $TYPE == "g" ]]; then
+	TEMPLATE=$(echo -e "$TEMPLATE_HEADER\n\n$TEMPLATE_GEN_FN\n\n$TEMPLATE_MAIN_HEADER\n\n$TEMPLATE_RNG\n\n$TEMPLATE_CALL_GEN\n}" )
+else
+	echo -e "ERROR: Invalid type: $TYPE\n"
+	print_help
+fi
+
+
+if [[ -f $FILE ]]; then
+	echo -e "ERROR: $FILE already exists\n"
+	exit
+else
+	echo "$TEMPLATE"
+    # cp "$TEMPLATE_PATH" $FILE && nvim $FILE
 fi
diff --git a/bin/cpRun b/bin/cpRun
--- a/bin/cpRun
+++ b/bin/cpRun
@@ -1,12 +1,126 @@
 #!/bin/bash
 
-FILE="${1%.*}.cpp"
-OUTFILE=$2
-COMPILE_FLAGS=(-std=c++20 -Wshadow -Wall -fsanitize=address -fsanitize=undefined -D_GLIBCXX_DEBUG -g)
+# Functions
+function print_help {
+	SCRIPT_NAME=$(basename $BASH_SOURCE)
+	echo -e "USAGE"
+	echo -e "\t$SCRIPT_NAME [OPTION]... <program[.cpp]>"
+	echo -e "\t\tCompile/Run the specified C++ program\n"
+	echo -e "\t$SCRIPT_NAME [OPTION]... -t <program[.cpp]> [validator[.cpp]] [generator[.cpp]]"
+	echo -e "\t\tTest the specified C++ program using a validator and generator.\n"
+	echo -e "\t$SCRIPT_NAME [-h]\n\t\tDisplay this text\n"
 
-if [ -z "$OUTFILE" ]
-then
-	OUTFILE="a.out"
+	echo -e "ARGUMENTS"
+	echo -e "\tprogram"
+	echo -e "\t\tThe c++ program to run/test. It should read the testcase generated from the"
+	echo -e "\t\tgenerator and print out the result.\n"
+	echo -e "\tvalidator"
+	echo -e "\t\tThe c++ program that validates the program. Should work the same as the program,"
+	echo -e "\t\texcept it should also read in the output from the program and exit with error if"
+	echo -e "\t\tthe program produced an incorrect result.\n\t\tDefaults to (program)val.cpp\n"
+	echo -e "\tgenerator"
+	echo -e "\t\tShould take a seed as argument, and print out a valid testcase for the program."
+	echo -e "\t\tDefaults to (program)gen.cpp\n"
+
+	echo -e "OPTIONS"
+	echo -e "\t-h\n\t\tDisplay this text\n"
+	echo -e "\t-o, -O\n\t\tCompile with optimizations enabled\n"
+	echo -e "\t-t\n\t\tTest program instead of just running it\n"
+
+	exit 1
+}
+
+function cleanup {
+	[ -e "$PROGRAM" ] && rm $PROGRAM
+	[ -e "$GENERATOR" ] && rm $GENERATOR
+	[ -e "$VALIDATOR" ] && rm $VALIDATOR
+	exit
+}
+
+# Variables
+PROGRAM="a.out"
+TEST_FLAG=false
+
+COMPILE_FLAGS=(-std=c++20 -Wshadow -Wall -fsanitize=address -fsanitize=undefined -D_GLIBCXX_DEBUG -g)
+OPTIMIZED_COMPILE_FLAGS=(-std=c++20 -O2 -Wno-unused-result -Wshadow -Wall)
+
+# Parse arguments
+while getopts hoOt opt
+do
+	case "${opt}" in
+		h) print_help;;
+		o) COMPILE_FLAGS=("${OPTIMIZED_COMPILE_FLAGS[@]}");;
+		O) COMPILE_FLAGS=("${OPTIMIZED_COMPILE_FLAGS[@]}");;
+		t) TEST_FLAG=true;;
+		*) print_help;;
+	esac
+done
+shift $((OPTIND - 1))
+
+PROGRAM_FILE="${1%.*}.cpp"
+
+# Cleanup on user interrupt
+trap cleanup SIGINT
+
+# Perform action
+if [[ $TEST_FLAG == false ]]; then
+	# Validate input
+	if [[ $# == 0 || $# > 1 ]]; then
+		print_help
+	fi
+
+	# Run program
+	echo "RUNNING $PROGRAM_FILE"
+	g++ $PROGRAM_FILE ${COMPILE_FLAGS[*]} -o $PROGRAM && eval " ./$PROGRAM" && rm "./$PROGRAM"
+else
+	# Validate input
+	if [[ $# == 0 || $# > 3 ]]; then
+		print_help
+	fi
+
+	BASE_FILENAME="${PROGRAM_FILE%.*}"
+	VALIDATOR_FILE="${BASE_FILENAME}val.cpp"
+	GENERATOR_FILE="${BASE_FILENAME}gen.cpp"
+	VALIDATOR="val.out"
+	GENERATOR="gen.out"
+
+	if [[ $# > 1 ]]; then
+		VALIDATOR_FILE="${2%.*}.cpp"
+	fi
+	if [[ $# > 2 ]]; then
+		GENERATOR_FILE="${3%.*}.cpp"
+	fi
+
+	echo "Testing $PROGRAM_FILE (^C to exit)"
+
+	# Compile programs
+	g++ $PROGRAM_FILE   ${COMPILE_FLAGS[*]} -o $PROGRAM
+	g++ $VALIDATOR_FILE ${COMPILE_FLAGS[*]} -o $VALIDATOR
+	g++ $GENERATOR_FILE ${COMPILE_FLAGS[*]} -o $GENERATOR
+
+	# Test program
+	for((i = 1; ; ++i)) do
+		echo -n "Test $i: "
+
+		INPUT=$(eval " ./$GENERATOR" $i)
+		PROGRAM_OUTPUT=$(printf '%s\n' "$INPUT" | eval "./$PROGRAM")
+		VALIDATOR_OUTPUT=$(printf '%s\n%s\n' "$INPUT" "$PROGRAM_OUTPUT" | eval "./$VALIDATOR")
+		VALIDATOR_RESULT="$?"
+
+		if [[ $VALIDATOR_RESULT == 0 ]]; then
+			echo "correct"
+		else
+			echo "incorrect"
+			echo "-------------------INPUT----------------------"
+			echo $INPUT
+			echo "-------------------OUTPUT---------------------"
+			echo $PROGRAM_OUTPUT
+			echo "------------------CORRECT---------------------"
+			echo $VALIDATOR_OUTPUT
+			break
+		fi
+	done
 fi
 
-g++ $FILE ${COMPILE_FLAGS[*]} -o $OUTFILE && eval " ./$OUTFILE" && rm "./$OUTFILE"
+# Cleanup on exit
+cleanup
